apiVersion: v1
kind: Service
metadata:
  name: reviews
  namespace: apollo-operator
spec:
  selector:
    app: reviews
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reviews
  name: reviews
  namespace: apollo-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
  strategy: {}
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
      - image: ghcr.io/example/reviews:latest
        name: reviews
        ports:
        - containerPort: 4000
        resources: {}
