apiVersion: apollographql.com/v1alpha2
kind: Supergraph
metadata:
  name: router-retail
spec:
  replicas: 2
  schema:
    resource:
      name: retail
  routerConfig:
    homepage:
      enabled: false
    sandbox:
      enabled: true
    supergraph:
      introspection: true
    # tls:
    #   subgraph:
    #     all:
    #       certificate_authorities: /certs/mntv_internal_root_ca.crt
  podTemplate:
    routerVersion: 2.7.0
    spec:
      volumes:
        - name: apollorouter-ca-cert
          configMap:
            name: apollorouter-ca-cert
      containers:
        - name: router
          volumeMounts:
            - name: apollorouter-ca-cert
              mountPath: /certs  # Replace with desired mount path
              readOnly: true
